#!/usr/bin/env python

"""
This small application tests whether kjBuckets has already been installed
and if not does so
"""

import imp, sys, os

def test_module(module_name) :
  passed = 1
  try:
    loc = imp.find_module(module_name)
  except :
    passed = 0
  return (passed)

if __name__ == "__main__" :
  if not test_module('kjbuckets'):
    os.system("cd KJBUCKETS; python setup.py build_ext -i; mv kjbuckets.so ..")
